#!/bin/sh
#
# Script to monitor disk usage.
#
# By PatrickDK
# Modify by flipflip
#
# Parameters understood:
#
#       config   (required)
#       autoconf (optional - used by munin-config)
#
# $Log$
#
# Magic markers (optional - used by munin-config and installation
# scripts):
#
#%# family=auto
#%# capabilities=autoconf

VG=`basename $0 | sed 's/^lvm_usage_//'`
I=""
LVS=$(which lvs)
VGS=$(which vgs)
AWK=$(which awk)
GREP=$(which grep)

clean_name() {
    echo $1 | sed 's/[\/.-]/_/g'
}

case $1 in
    autoconf)
        if [ -x $LVS ]; then
            echo yes
            exit 0
        elif [ -x $VGS ]; then
            echo yes
            exit 0
        else
            echo no '(lvm (lvs or vgs) programs not found)'
            exit 1
        fi
        exit 0
        ;;

    config)
        echo "graph_title Logical Volume usage $VG"
        echo "graph_args --base 1024 --lower-limit 0"
        echo "graph_category disk"
        echo "graph_info This graph shows disk usage on the machine."
        echo "free.label free"
        echo "free.draw AREA"
        $LVS --units b --nosuffix --noheadings | $GREP $VG | while read I; do
            NAME=`clean_name $I`
            echo -n "$NAME.label "
            echo $I | $AWK '{ print $1 }'
            echo "$NAME.draw STACK"
        done
        exit 0
        ;;

    *)
        I=`$VGS --units b --nosuffix --noheadings | grep $VG`
        echo -n "free.value "
        echo $I | $AWK '{ print $7 }'

        $LVS --units b --nosuffix --noheadings | $GREP $VG | while read I; do
            NAME=`clean_name $I`
            echo -n "$NAME.value "
            echo $I | $AWK '{ print $4 }'
        done
        exit 0
esac
